import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const initialReports = [
  { id: 'R-701', time: '14:32:08', source: 'Raven-2 / UAS', domain: 'AIR', headline: 'Two thermal signatures near OBJ KESTREL', detail: 'Confidence 0.72 · 90 sec old · vector 118°', state: 'stale', icon: '◌' },
  { id: 'R-702', time: '14:34:41', source: 'Alpha 1-1', domain: 'LAND', headline: 'Route ECHO is clear for movement', detail: 'Confidence 0.86 · voice report', state: 'live', icon: '⌁' },
  { id: 'R-703', time: '14:35:03', source: 'NetWatch', domain: 'CYBER', headline: 'Possible credential replay on logistics node', detail: 'Confidence 0.58 · corroboration pending', state: 'live', icon: '◇' },
  { id: 'R-704', time: '14:35:17', source: 'Echo 3', domain: 'EW', headline: 'GNSS drift detected. Position unreliable.', detail: 'Confidence 0.91 · 2 km radius uncertainty', state: 'jammed', icon: '▧' },
];

const initialEvents = [
  { time: '14:31:12', tag: 'SYSTEM', text: 'Exercise clock started · phase 02 / contested approach' },
  { time: '14:32:08', tag: 'AIR', text: 'Raven-2 report received with 90 sec latency' },
  { time: '14:34:41', tag: 'LAND', text: 'Alpha 1-1 authenticated on primary voice net' },
  { time: '14:35:17', tag: 'EW', text: 'GNSS degradation crossed amber threshold' },
];

const decisions = [
  { time: '14:32:44', actor: 'Lt. A. Mehta', action: 'HOLD', rationale: 'Await visual confirmation before committing reserve', confidence: 61 },
  { time: '14:34:58', actor: 'Sgt. K. Rao', action: 'REROUTE', rationale: 'Move Alpha 1-1 to Route FOXTROT; preserve tempo', confidence: 74 },
];

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span>; }
function Badge({ children, tone = 'neutral' }) { return <span className={`badge ${tone}`}>{children}</span>; }

function App() {
  const [reports, setReports] = useState(initialReports);
  const [events, setEvents] = useState(initialEvents);
  const [decisions, setDecisions] = useState(decisions);
  const [activeTab, setActiveTab] = useState('cockpit');
  const [selectedDomain, setSelectedDomain] = useState('ALL');
  const [degradation, setDegradation] = useState(42);
  const [latency, setLatency] = useState(68);
  const [dropout, setDropout] = useState(21);
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);
  const [decisionText, setDecisionText] = useState('');
  const [decisionType, setDecisionType] = useState('HOLD');
  const [confidence, setConfidence] = useState(64);

  const visibleReports = useMemo(() => selectedDomain === 'ALL' ? reports : reports.filter(r => r.domain === selectedDomain), [reports, selectedDomain]);
  const addEvent = (tag, text) => setEvents(current => [{ time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }), tag, text }, ...current]);
  const inject = (kind) => {
    const label = kind === 'dropout' ? 'Primary voice net dropout injected for Alpha 1-1' : kind === 'conflict' ? 'Conflicting report injected: Route ECHO not clear' : 'Telemetry delay increased to 180 sec';
    addEvent('INJECT', label);
    if (kind === 'dropout') setDropout(v => Math.min(95, v + 12));
    if (kind === 'delay') setLatency(v => Math.min(95, v + 18));
    if (kind === 'conflict') setReports(rs => rs.map(r => r.id === 'R-702' ? { ...r, headline: 'CONFLICT: Route ECHO status disputed', state: 'conflict', detail: 'Confidence 0.42 · conflicting Echo 3 voice report' } : r));
  };
  const sendMessage = () => { if (!message.trim()) return; addEvent('TEAM', `You → ALL: ${message.trim()}`); setMessage(''); setSent(true); setTimeout(() => setSent(false), 1600); };
  const logDecision = () => { if (!decisionText.trim()) return; const d = { time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }), actor: 'You / OC', action: decisionType, rationale: decisionText.trim(), confidence: Number(confidence) }; setDecisions(ds => [d, ...ds]); addEvent('DECISION', `${decisionType} logged at ${confidence}% confidence`); setDecisionText(''); };
  const exportAAR = () => { const blob = new Blob([JSON.stringify({ exercise: 'IRON LANTERN · Phase 02', exportedAt: new Date().toISOString(), degradation: { comms: degradation, latency, dropout }, decisions, eventTimeline: events }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'sentinel-grid-aar.json'; a.click(); URL.revokeObjectURL(url); addEvent('AAR', 'After-action report exported for instructor review'); };

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><span></span><span></span><span></span></div><div><strong>SENTINEL</strong><small>GRID / TRAINING OS</small></div></div>
      <div className="exercise-card"><div className="eyebrow">ACTIVE EXERCISE</div><h3>IRON LANTERN</h3><p>PHASE 02 · CONTESTED APPROACH</p><div className="exercise-meta"><span><i className="pulse"></i> LIVE</span><span>00:18:42</span></div></div>
      <nav className="nav"><div className="nav-label">OPERATIONS</div>{[['cockpit','◈','Command cockpit'],['team','⌁','Team channel'],['aar','≡','AAR & replay']].map(([tab, icon, label]) => <button key={tab} className={activeTab === tab ? 'nav-item active' : 'nav-item'} onClick={() => setActiveTab(tab)}><Icon>{icon}</Icon>{label}{tab === 'team' && <em>3</em>}</button>)}<div className="nav-label instructor-label">INSTRUCTOR</div><button className="nav-item" onClick={() => { setActiveTab('cockpit'); addEvent('INSTR', 'Instructor console opened'); }}><Icon>⚙</Icon>Scenario controls</button><button className="nav-item" onClick={exportAAR}><Icon>⇩</Icon>Export AAR</button></nav>
      <div className="sidebar-footer"><div className="user-dot">AM</div><div><strong>Arjun Mehta</strong><small>OC / ALPHA CELL</small></div><span className="more">•••</span></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><div className="breadcrumb">EXERCISE / IRON LANTERN / <span>COMMAND COCKPIT</span></div><h1>{activeTab === 'cockpit' ? 'Decision cockpit' : activeTab === 'team' ? 'Team channel' : 'AAR & replay'}</h1></div><div className="top-actions"><div className="sync"><span className="sync-dot"></span> SYNCED <small>14:35:42Z</small></div><button className="ghost-btn"><span>?</span> Brief</button><button className="avatar">AM</button></div></header>
      {activeTab === 'cockpit' && <><section className="status-strip"><div className="status-main"><span className="status-icon">!</span><div><strong>COMMS DEGRADED</strong><span>Decision quality window is narrowing. Verify before commit.</span></div></div><div className="status-metrics"><div><small>NETWORK HEALTH</small><strong className="amber-text">{100 - degradation}%</strong></div><div><small>AVG LATENCY</small><strong>{latency}s</strong></div><div><small>ACTIVE NODES</small><strong>08 <span className="muted">/ 12</span></strong></div></div></section>
      <div className="content-grid"><section className="left-column"><div className="section-head"><div><div className="eyebrow">MULTI-DOMAIN FEED</div><h2>Common operating picture <Badge tone="live">LIVE</Badge></h2></div><div className="feed-actions"><button className="icon-btn">⊞</button><button className="icon-btn">⋮</button></div></div><div className="map-panel"><div className="map-top"><div className="map-legend"><span><i className="legend-dot blue"></i> FRIENDLY</span><span><i className="legend-dot amber"></i> UNCERTAIN</span><span><i className="legend-dot red"></i> THREAT</span></div><div className="map-time">T+00:18:42 · 14:35:42Z</div></div><div className="map-grid"><div className="contour contour-a"></div><div className="contour contour-b"></div><div className="route route-one">ROUTE ECHO</div><div className="route route-two">ROUTE FOXTROT</div><div className="map-label obj">OBJ<br/><b>KESTREL</b></div><div className="marker friendly m1"><span>▣</span><small>A1-1</small></div><div className="marker friendly m2"><span>▣</span><small>A1-2</small></div><div className="marker uncertain m3"><span>◇</span><small>RAVEN-2</small></div><div className="marker threat m4"><span>▲</span><small>?</small></div><div className="uncertainty-ring"></div><div className="map-scale">GRID 18T · 1:25,000 <span>+</span><span>−</span></div></div></div><div className="section-head compact"><div><div className="eyebrow">DECISION LOG</div><h2>What the team knows</h2></div><div className="filter-pills">{['ALL','LAND','AIR','CYBER','EW'].map(d => <button key={d} className={selectedDomain === d ? 'filter active' : 'filter'} onClick={() => setSelectedDomain(d)}>{d}</button>)}</div></div><div className="reports-list">{visibleReports.map(r => <div className={`report-row ${r.state}`} key={r.id}><div className="report-icon">{r.icon}</div><div className="report-copy"><div className="report-top"><Badge tone={r.domain.toLowerCase()}>{r.domain}</Badge><span className="report-source">{r.source}</span><span className="report-time">{r.time}</span></div><strong>{r.headline}</strong><p>{r.detail}</p></div><div className="report-state">{r.state === 'live' ? <span className="fresh">● LIVE</span> : r.state === 'conflict' ? <span className="conflict-text">↯ CONFLICT</span> : <span className="stale-text">◷ {r.state.toUpperCase()}</span>}</div></div>)}</div></section>
      <aside className="right-column"><div className="panel-head"><div><div className="eyebrow">INSTRUCTOR CONSOLE</div><h2>Friction controls</h2></div><span className="lock">⌘</span></div><p className="panel-note">Inject uncertainty without breaking exercise flow. Changes are visible to instructor only.</p><Control label="COMMS DEGRADATION" value={degradation} suffix="%" onChange={setDegradation}/><Control label="TELEMETRY LATENCY" value={latency} suffix="sec" onChange={setLatency}/><Control label="VOICE DROPOUT" value={dropout} suffix="%" onChange={setDropout}/><div className="inject-grid"><button onClick={() => inject('delay')}><span>◴</span> Delay feed</button><button onClick={() => inject('dropout')}><span>⌁</span> Drop node</button><button onClick={() => inject('conflict')}><span>↯</span> Conflict report</button></div><div className="panel-divider"></div><div className="panel-head small"><h3>Team presence</h3><Badge tone="live">4 ONLINE</Badge></div><div className="presence"><Presence initials="AM" name="You / OC" role="ALPHA CELL" active/><Presence initials="KR" name="K. Rao" role="ALPHA 1-1"/><Presence initials="DS" name="D. Singh" role="RAVEN-2"/><Presence initials="NP" name="N. Patel" role="NETWATCH"/></div></aside></div>
      <section className="bottom-grid"><div className="timeline-panel"><div className="section-head compact"><div><div className="eyebrow">EVENT STREAM</div><h2>Exercise timeline</h2></div><span className="live-indicator"><i className="pulse"></i> CAPTURING</span></div><div className="event-list">{events.slice(0, 5).map((e, i) => <div className="event-row" key={i}><span className="event-time">{e.time}</span><Badge tone={e.tag.toLowerCase()}>{e.tag}</Badge><span>{e.text}</span></div>)}</div></div><div className="decision-panel"><div className="section-head compact"><div><div className="eyebrow">YOUR ACTION</div><h2>Log a decision</h2></div></div><div className="decision-form"><div className="select-row">{['HOLD','REROUTE','COMMIT','REPORT'].map(t => <button key={t} className={decisionType === t ? 'decision-chip active' : 'decision-chip'} onClick={() => setDecisionType(t)}>{t}</button>)}</div><textarea value={decisionText} onChange={e => setDecisionText(e.target.value)} placeholder="State your intent and rationale…"/><div className="confidence-row"><label>CONFIDENCE <b>{confidence}%</b></label><input type="range" min="1" max="100" value={confidence} onChange={e => setConfidence(e.target.value)}/><button className="primary-btn" onClick={logDecision}>LOG DECISION <span>↗</span></button></div></div></div></section></>}
      {activeTab === 'team' && <TeamPanel message={message} setMessage={setMessage} sendMessage={sendMessage} sent={sent} addEvent={addEvent}/>} {activeTab === 'aar' && <AARPanel decisions={decisions} events={events} exportAAR={exportAAR}/>}</main>
  </div>;
}

function Control({ label, value, suffix, onChange }) { return <div className="control"><div><label>{label}</label><strong>{value}<small>{suffix}</small></strong></div><input type="range" min="0" max="100" value={value} onChange={e => onChange(Number(e.target.value))}/><div className="control-scale"><span>LOW</span><span>HIGH</span></div></div>; }
function Presence({ initials, name, role, active }) { return <div className="presence-row"><div className={`mini-avatar ${active ? 'me' : ''}`}>{initials}</div><div><strong>{name}</strong><small>{role}</small></div><span className={active ? 'online-dot' : 'away-dot'}></span></div>; }
function TeamPanel({ message, setMessage, sendMessage, sent, addEvent }) { const [channel, setChannel] = useState('ALPHA CELL'); const chats = [{ who:'K. Rao', initials:'KR', time:'14:34:58', text:'Alpha 1-1 confirms ECHO clear. Moving to phase line.' }, { who:'D. Singh', initials:'DS', time:'14:35:06', text:'Raven-2 sees thermal bloom, but feed is stale. Requesting tasking.' }, { who:'N. Patel', initials:'NP', time:'14:35:21', text:'NetWatch: GNSS drift is spreading east. Recommend manual reference.' }]; return <div className="team-layout"><section className="chat-panel"><div className="section-head"><div><div className="eyebrow">TEAM CHANNEL</div><h2>{channel} <span className="channel-lock">⌁</span></h2></div><Badge tone="live">DEGRADED NET</Badge></div><div className="chat-messages">{chats.map(c => <div className="chat-message" key={c.who}><div className="mini-avatar">{c.initials}</div><div><div className="chat-meta"><strong>{c.who}</strong><span>{c.time}</span></div><p>{c.text}</p></div></div>)}<div className="system-message">Messages may be delayed or dropped. Verify critical reports.</div></div><div className="composer"><textarea value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => { if(e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); } }} placeholder="Transmit to ALPHA CELL…"/><button className="primary-btn" onClick={sendMessage}>{sent ? 'SENT ✓' : 'TRANSMIT ↗'}</button></div></section><aside className="team-side"><div className="eyebrow">CHANNELS</div>{['ALPHA CELL','NETWATCH','RAVEN-2','INSTRUCTOR'].map(c => <button key={c} className={channel === c ? 'channel active' : 'channel'} onClick={() => setChannel(c)}><span>#</span>{c}<small>{c === 'ALPHA CELL' ? '3' : ''}</small></button>)}<div className="side-tip"><strong>Training cue</strong><p>Use plain language. Assume a 30–90 sec delay on every transmission.</p></div></aside></div>; }
function AARPanel({ decisions, events, exportAAR }) { return <div className="aar-layout"><section className="aar-summary"><div className="section-head"><div><div className="eyebrow">AFTER-ACTION REVIEW</div><h2>IRON LANTERN / PHASE 02</h2></div><button className="primary-btn" onClick={exportAAR}>EXPORT JSON ↗</button></div><div className="score-row"><div><small>DECISIONS LOGGED</small><strong>{decisions.length}</strong></div><div><small>AVG CONFIDENCE</small><strong>{Math.round(decisions.reduce((a,d) => a + d.confidence, 0) / decisions.length)}<em>%</em></strong></div><div><small>COMMS EXPOSURE</small><strong className="amber-text">HIGH</strong></div><div><small>REPORT STATUS</small><strong className="green-text">READY</strong></div></div><div className="aar-table"><div className="table-head"><span>TIME</span><span>ACTOR</span><span>ACTION</span><span>RATIONALE / CONFIDENCE</span></div>{decisions.map((d, i) => <div className="table-row" key={i}><span>{d.time}</span><span>{d.actor}</span><Badge tone={d.action.toLowerCase()}>{d.action}</Badge><span>{d.rationale}<b>{d.confidence}%</b></span></div>)}</div></section><aside className="replay-card"><div className="eyebrow">REPLAY INDEX</div><h3>Decision timeline</h3><div className="replay-line">{events.slice(0, 5).map((e, i) => <div className="replay-item" key={i}><i className={i === 0 ? 'replay-dot current' : 'replay-dot'}></i><small>{e.time}</small><span>{e.text}</span></div>)}</div></aside></div>; }

createRoot(document.getElementById('root')).render(<App />);
